### ISSUE TITLE
 [MAC-Chrome-850-댓글] 렌더링 위치 및 작성 시간 표시 문제 

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-swan-song-community-fe#10]
**버그 설명** 버그에 대한 명확하고 간결한 설명해주세요.
1. 댓글 작성 시 최신 댓글이 위로 정렬 되지만 페이지를 새로고침 하면 최신 댓글이 아래로 정렬됩니다.
2. 댓글 작성 시간이 두 줄로 나뉘어 표시 됩니다. 

**재현하는 방법** 동작을 재현하는 단계:

1. 게시글 상세 페이지로 이동합니다.
2. 댓글을 작성합니다. 
3. 작성한 댓글이 상단에 위치하는 것을 확인합니다.
4. 다른 페이지로 이동 했다가 다시 들어와 댓글 목록을 확인합니다. 
5. 작성한 댓글이 하단에 위치하는 것을 확인합니다. 

**예상한 동작** 예상했던 일에 대한 명확하고 간결한 설명해주세요.
1. 댓글을 작성하면 최신 댓글이 위에 위치하고 페이지 전환과 상관 없이 정렬이 유지 됩니다. 
2. 댓글 작성 시간은 한 줄로 표시됩니다. 

**스크린샷** 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/8f6c40e7-9826-4ebd-bc60-299059918636)
![image](https://github.com/user-attachments/assets/c60f7c7b-b93f-40b5-9052-8f1ae848d330)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by Unagi-zoso** [comment]
좋네요.
닉네임 최대길이를 고려해서 너비를 줘야겠어요.
감사합니다.

**Comment by Unagi-zoso** [comment]
여러모로 UI 에 대해 많이 생각할 수 있었던 좋은 이슈였네요!

[850 x 1080]
![스크린샷 2024-12-19 오후 2 38 20](https://github.com/user-attachments/assets/e6535384-778d-4ce6-a818-162ecf18a7aa)
