### ISSUE TITLE
 [MAC-Chrome-850-회원 탈퇴]  회원 탈퇴 후 Cannot GET 오류

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-swan-song-community-fe#11]
**버그 설명** 버그에 대한 명확하고 간결한 설명해주세요.
회원 탈퇴 후 로그인 페이지로 리다이렉트되지 않고 "Cannot GET /user-info-modify"라는 오류 메시지가 표시됩니다.

**재현하는 방법** 동작을 재현하는 단계:
1. 로그인 후 회원 정보 수정 페이지로 이동합니다.
2. 회원 탈퇴를 진행합니다. 
3. 오류를 확인합니다. 

**예상한 동작** 예상했던 일에 대한 명확하고 간결한 설명해주세요.
회원 탈퇴가 성공적으로 동작한 뒤 로그인 페이지로 이동 

**스크린샷** 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/0612f7bd-2e03-453f-801e-b04eb7f6b5d9)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by Unagi-zoso** [comment]
오오 감사합니다. 좋네요!

**Comment by Unagi-zoso** [comment]
**회원탈퇴 버튼의 type 이 Submit 이였던 것**과 **현재 index 페이지 제외 url 접근이 막혀있던게** 문제였던걸로 파악됩니다.
**Submit 의 기본동작**으로 인해 현재 페이지로 한 번 더 **리다이렉션**이 되었고 이 **url 이 index 가 아니라 Cannot GET** 이 발생했습니다.

해결 방법은
리액트 배포 서버에서 index 페이지 제외 url 에도 접근할 수 있도록 하였습니다.
회원탈퇴 버튼 타입을 변경했습니다. (submit -> button) 그리고 동작 방식을 window.confirm 대신 직접 모달로 구현했습니다. (사용자 경험 향상)

**Comment by Unagi-zoso** [comment]
요 이슈도 잘 해결되어 닫겠습니다.
비슷한 문제가 또 발생한다면 편하게 다시 열어주세요.

![스크린샷 2024-12-19 오후 2 41 05](https://github.com/user-attachments/assets/1df712d8-f373-4dff-b556-036b2eff32c7)

![스크린샷 2024-12-19 오후 2 41 26](https://github.com/user-attachments/assets/b4b1e3a7-ebea-4b0e-aa3c-35e40a348bfd)
![스크린샷 2024-12-19 오후 2 41 49](https://github.com/user-attachments/assets/701c87f4-4608-456c-93d3-d6b3ec2c20a5)
