### ISSUE TITLE
 [MAC-Chrome-850-게시글] 작성한 게시글의 수정, 삭제 버튼이 표시되지 않음  

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-swan-song-community-fe#12]
**버그 설명** 버그에 대한 명확하고 간결한 설명해주세요.
게시글 작성 후 게시글 상세 페이지로 이동했는데 수정 및 삭제하기 버튼이 표시되지 않습니다. 

**재현하는 방법** 동작을 재현하는 단계:
1. 게시글을 작성합니다.
2. 작성한 게시글을 클릭해 상세 보기 페이지로 이동합니다. 
3. 게시글 수정 및 삭제 버튼이 표시되지 않는 것을 확인합니다. 

**예상한 동작** 예상했던 일에 대한 명확하고 간결한 설명해주세요.
게시글 작성자는 상세 페이지에서 본인의 게시글에 대해 수정 및 삭제 버튼이 표시되어야 합니다.

**스크린샷** 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/c396c38a-e229-4ae5-8742-8905c86da209)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by Unagi-zoso** [comment]
거의 다 잡힌 이슈긴한데 혹시 회원 탈퇴 후 새로운 계정으로 접근했었나요?

문제 내용은 비동기 호출을 받지 못한채 작성자 검증을 해서 발생한 것으로 판단 중입니다.

**Comment by Unagi-zoso** [comment]
전역 컨텍스트로 userId 를 다루려하다 생겨난 문제 같네요. 새로운 방식을 도입하면서 생겨난 문젠데 아직 정확한 내부 동작을 이해하지 못해서 다른 방식으로 해결했습니다.
요거 참 어려운 문제네요. (좋은 이슈라는 뜻 😋👍)

일단은 해결한 이슈로 판단되어 닫도록 하겠습니다.
비슷한 문제가 또 발생한다면 편하게 다시 열어주세요!

---

현재는 수정, 삭제가 잘 표현됩니다.

![스크린샷 2024-12-19 오후 2 45 57](https://github.com/user-attachments/assets/4bec9ea0-494d-46b9-8bb0-0b030b9211bc)
