### ISSUE TITLE
 [Windows-Chrome-1920-인덱스 페이지] 인덱스 페이지에서 refresh시 redirection 오류

### ISSUE THREAD

**Issue by JiwonHwang01** [100-hours-a-week/2-swan-song-community-fe#2]
**버그 설명** index 페이지에서 refresh 하면 redirection 오류

**재현하는 방법** 
1. Go to '/' 
2. Refresh
3. see Error "Cannot GET /login"

**예상한 동작** 
/login 이 정상적으로 표시됨

**스크린샷** 
![image](https://github.com/user-attachments/assets/b54a56f9-39e4-414b-aee2-80747a041a38)

**데스크톱(다음 정보를 작성해 주세요):**

-   OS: Windows 11
-   Browser: Chrome

**Comment by Unagi-zoso** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Unagi-zoso** [comment]
해결하여 배포하였습니다.
issue 닫겠습니다!
