### ISSUE TITLE
 [Windows-Chrome-1920-register] 회원가입 닉네임 중복 확인 중 에러

### ISSUE THREAD

**Issue by JiwonHwang01** [100-hours-a-week/2-swan-song-community-fe#3]
**버그 설명** 버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법** 동작을 재현하는 단계:

1. Go to '/register'
2. Put information properly
3. See username helper-text "* 닉네임 중복 확인 중 오류가 발생했습니다."

**예상한 동작**
회원가입 버튼의 활성화

**스크린샷**
![image](https://github.com/user-attachments/assets/e612fc9f-8191-4b6f-a70e-99d032a52212)

**데스크톱(다음 정보를 작성해 주세요):**

-   OS: Windows 11
-   Browser: Chrome

**Comment by Unagi-zoso** [comment]
요건 네트워크 문제였네요. 제대로 검사 API 날라가지 못해 에러가 발생했습니다.
현재는 해결되었습니다.

감사합니다.
