### ISSUE TITLE
 [Windows-Chrome-1920] Post 상세 보기의 width

### ISSUE THREAD

**Issue by JiwonHwang01** [100-hours-a-week/2-swan-song-community-fe#4]
**버그 설명** 
버그는 아니고 큰 화면에서 보면 상세 보기의 width가 헤더 너비를 벗어나서 수정하면 좋을 것 같습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/58643ffe-a248-416a-9248-5d282fe1e8ba)

**데스크톱:**
-   OS: Windows 11
-   Browser: Chrome

**Comment by Unagi-zoso** [comment]
좋네용

**Comment by Unagi-zoso** [comment]
해결하여 배포하였습니다.
issue 닫겠습니다!

[1920 x 1080]
![스크린샷 2024-12-19 오후 2 12 20](https://github.com/user-attachments/assets/17ee42b6-c9cd-4c24-99bc-52fe2861a39e)

[840 x 1080]
![스크린샷 2024-12-19 오후 2 13 45](https://github.com/user-attachments/assets/ac15bb1a-12f0-4204-a43f-57ff5c4fe847)

**Comment by Unagi-zoso** [comment]
해결하여 배포하였습니다.
issue 닫겠습니다!
똑같은 문제가 발견된다면 다시 오픈해주세용

[1920 x 1080]
![스크린샷 2024-12-19 오후 2 16 26](https://github.com/user-attachments/assets/b0931d17-e570-49b6-9e0e-146b335ff36a)

[840 x 1080]
![스크린샷 2024-12-19 오후 2 16 13](https://github.com/user-attachments/assets/1bed71fe-08cc-4624-ab8c-0725cfd7ee20)
