### ISSUE TITLE
 [MAC-Chrome-850-로그인] helper text 

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-swan-song-community-fe#5]
**버그 설명** 버그에 대한 명확하고 간결한 설명해주세요.
로그인 화면에서 이메일 또는 비밀번호 입력 형식이 맞지 않을 경우 helper text에 "아이디나 비밀번호가 형식에 맞지 않습니다."라는 오류 메시지가 표시됩니다. 
그런데 어떤 입력란에 문제가 있는지 명확하지 않아 사용자 경험이 저하됩니다.

**재현하는 방법** 동작을 재현하는 단계:
1. 로그인 화면으로 이동합니다.
2. 이메일 또는 비밀번호 입력란에 잘못된 형식의 값을 입력하거나 또는 한 쪽의 값을 비워둡니다. 
3. "아이디나 비밀번호가 형식에 맞지 않습니다."라고 나오는 helper text를 확인합니다. 

**예상한 동작** 예상했던 일에 대한 명확하고 간결한 설명해주세요.
이메일과 비밀번호 입력란에 각각 매핑된 helper text가 표시되어야 합니다.

**스크린샷** 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/ed25884b-b3fd-4581-910b-3756eccd42b4)

**데스크톱(다음 정보를 작성해 주세요):**
**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by Unagi-zoso** [comment]
좋네요!

**Comment by Unagi-zoso** [comment]
해결하여 배포하였습니다.
issue 닫겠습니다!
똑같은 문제가 발견된다면 다시 오픈해주세용

![스크린샷 2024-12-19 오후 2 17 50](https://github.com/user-attachments/assets/f741d327-a75b-44b3-8787-928b07c0a103)

[정상 입력 시]
![스크린샷 2024-12-19 오후 2 18 28](https://github.com/user-attachments/assets/839027a2-2a86-4788-932b-9b49f26355a6)
