### ISSUE TITLE
 [MAC-크롬-회원정보 수정] 이미지 수정 버그

### ISSUE THREAD

**Issue by donet12** [100-hours-a-week/2-swan-song-community-fe#6]
**버그 설명** 
이미지를 등록하지않고 취소하면 오류가 발생합니다.
**재현하는 방법** 동작을 재현하는 단계:
1. 이미지 클릭
2. 취소
3. 오류발생

**예상한 동작** 
기존 이미지가 그대로 반영되기를 기대했습니다.

**스크린샷**

https://github.com/user-attachments/assets/e99b127b-bfb0-45da-9495-362f6c8c5321

**데스크톱:**
-   OS: [mac]
-   Browser [chrome]

**Comment by Unagi-zoso** [comment]
상당히 날카롭네요. 매우 좋습니다!

**Comment by Unagi-zoso** [comment]
아 이거 좀 알아봤는데

기존값 기준으로 변경된 부분이 없어서 실패하는거 같아요.
실제로 제 로직도 그렇고

같은 조건에서 닉네임을 변경해서 시도했을 경우 성공했습니다.

**Comment by Unagi-zoso** [comment]
요건 오류라기보단 스펙이라 이슈 닫을게요.
혹시나 이상 있다면 편하게 오픈해주세욧
