### ISSUE TITLE
 [MAC-크롬-게시물 상세페이지] 수정 버튼 문제

### ISSUE THREAD

**Issue by donet12** [100-hours-a-week/2-swan-song-community-fe#7]
**버그 설명** 
- 로그아웃하고 새로 회원가입하고 로그인했더니 그전 세션이 남아있는거같습니다. 게시글 수정이안됩니다.
**재현하는 방법** 
1. 회원가입 후 로그인
2. 게시글 작성
3. 로그아웃 후 회원가입 후 로그인
4. 게시글 작성
5. 게시글 수정이 이전 회원으로 되어있음

**예상한 동작** 예상했던 일에 대한 명확하고 간결한 설명해주세요.
- 현재 유저가 수정을 할수있기를 예상했습니다.

**스크린샷** 
![image](https://github.com/user-attachments/assets/8f0a239b-5082-4eac-bc46-e5120e3fa2b6)

![image](https://github.com/user-attachments/assets/4b06a732-6ceb-459f-b898-1903752f573d)
- 아까 로그아웃한 계정에만 수정버튼이 있음

**데스크톱(다음 정보를 작성해 주세요):**

-   OS: [MAC]
-   Browser [chrome]
-   Version [예) 22]

**추가적인 내용:** 여기에 문제에 대한 다른 컨텍스트를 추가해주세요.
- 수정버튼을 누르면 수정페이지까지 이동은 되지만 수정은 안되는거같습니다.

**Comment by Unagi-zoso** [comment]
좋습니다

**Comment by Unagi-zoso** [comment]
참 좋은 이슈였습니다.

문제 내용을 설명드리자면 리액트 SPA 환경의 전역 상태는 새로고침을 하지 않는 이상
초기화 되지 않습니다. 

그래서 새로고침 없이 로그아웃을 하게 될 시 전역 상태를 직접 초기화해주지 않으면 
다음 사용자가 이를 이어 사용할 수 있었습니다.

아주 예리한 부분을 잘 집어주신 이슈 같습니다!

짝짝짝

---

이것도 해결하여 배포하였습니다.
issue 닫겠습니다!
똑같은 문제가 발견된다면 다시 오픈해주세용


새 계정으로 로그인 했을 때 로그아웃 전,후 계정의 게시글 비교입니다.
(로그아웃 후 계정은 현재 로그인한 계정이 되겠습니다.)

[로그아웃 전 게시글]
![스크린샷 2024-12-19 오후 2 25 27](https://github.com/user-attachments/assets/6845b5ba-324e-4a17-beff-44d7c652543a)

[로그아웃 후 게시글 (현재 유저의 게시글)]
![스크린샷 2024-12-19 오후 2 27 24](https://github.com/user-attachments/assets/5b3515db-9f0d-40fc-8ab7-19f3b5c7624a)
