### ISSUE TITLE
 [MAC-크롬] 게시글 컨테이너 댓글,조회수 적용안됨

### ISSUE THREAD

**Issue by yosep98** [100-hours-a-week/2-swan-song-community-fe#8]
**버그 설명** 게시글에 댓글조회수 좋아요 값이 게시글 목록 랜더링된 부분과 다름 

**재현하는 방법** 동작을 재현하는 단계:

1. 해당 게시글 이동
2. 게시글 댓글 작성 혹은 좋아요 클릭
3. 게시글에 조회수,댓글수, 좋아요 수 변경됨

**예상한 동작** 게시글 목록으로 이동 하면 조회수,댓글수,좋아요  수 반영되길 예상했지만 그렇지 않음

**스크린샷** 
![스크린샷 2024-12-18 오후 4 29 56](https://github.com/user-attachments/assets/0e17439a-5978-490a-9e90-0f2bc79dbb63)
![스크린샷 2024-12-18 오후 4 30 01](https://github.com/user-attachments/assets/36551f1b-693b-44b4-b85a-6269b12faf42)

**데스크톱(다음 정보를 작성해 주세요):**

-   OS: MAC
-   Browser 크롬
-   Version 22

**Comment by yosep98** [comment]
로그아웃 후 접속할 경우 다시 랜더링이 잘 되는것을 보아 세션이 끊겨서 가져오질 못한건가? 하고 예상했습니다

**Comment by Unagi-zoso** [comment]
오호 이렇게도 생각할 수 있군요.

**Comment by Unagi-zoso** [comment]
전역 컨텍스트에 대해서 좀 더 공부할 수 있었던 이슈였네요.

아래 이미지는 게시글 리스트에서 볼 수 있는 정보의 변화 과정을 나타냈습니다.

![스크린샷 2024-12-19 오후 2 28 47](https://github.com/user-attachments/assets/bda943ca-bc52-432f-83ad-b57d3c3411eb)

![스크린샷 2024-12-19 오후 2 29 10](https://github.com/user-attachments/assets/bda7fb72-7a7a-422d-a4af-de374c0535ae)

![스크린샷 2024-12-19 오후 2 29 27](https://github.com/user-attachments/assets/e74702ef-fe43-49a1-b18e-5679aa127162)

---

이 이슈는 현재 해결되어서 닫도록 하겠습니다.
비슷한 문제가 또 발생한다면 편하게 열어주세요.
