### ISSUE TITLE
 [MAC-크롬] 게시글목록과 게시글 컨테이너 버튼위치 

### ISSUE THREAD

**Issue by yosep98** [100-hours-a-week/2-swan-song-community-fe#9]
**버그 설명** (버그는 아닌데..) 목록에 보여지는 좋아요  댓글 조회수 순서와 게시글에 보여지는 순서와 일치하지 않음
**재현하는 방법** 동작을 재현하는 단계:

1. 게시글 목록에서 게시글 이동

**예상한 동작** 좋아요 댓글 조회수 순서가 일치할거라 예상

**스크린샷** 
![스크린샷 2024-12-18 오후 4 41 48](https://github.com/user-attachments/assets/2608d5ca-27ae-4de9-9652-46c5ae726a69)
![스크린샷 2024-12-18 오후 4 41 58](https://github.com/user-attachments/assets/314e6da5-26f6-412d-a466-e87dcf5fc7f6)

**데스크톱:**
-   OS: [MAC]
-   Browser [ chrome]
-   Version [22]

**Comment by Unagi-zoso** [comment]
이런 UI 관련 이슈도 참 좋은것 같습니다.

좋아요 조회수 댓글 순서로 나타내게 했습니다.

![스크린샷 2024-12-19 오후 2 32 23](https://github.com/user-attachments/assets/85783bb9-86bf-4ccf-ba7d-0da459de6a05)
![스크린샷 2024-12-19 오후 2 32 33](https://github.com/user-attachments/assets/2de1b5f1-0562-4a9b-b21e-b972116e01ed)

---

이 이슈는 해결되었기에 닫겠습니다.
비슷한 문제가 다시 일어난다면 편하게 열어주세요.
